version: '3'
services:
  aggregator:
    image: aggregator:latest
    networks:
      - my-service-network
    ports:
      - 8082:8082
    environment:
      SPRING_OPTS: |
        --eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka
        --spring.kafka.bootstrap-servers=kafka:9092
        --spring.config.import=optional:configserver:http://config-server:8888
    
        
  
  tempSensor:
    image: temp-sensor:latest
    networks:
      - my-service-network
    ports:
      - 8081:8081
    environment:
      SPRING_OPTS: |
        --eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka

  humiditySensor:
    image: humidity-sensor:latest
    networks:
      - my-service-network
    ports:
      - 8080:8080
    environment:
      SPRING_OPTS: |
        --eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka

networks:
  my-service-network:
    external:
      name: my-network
