version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - my-network
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - my-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
  eurekaServer:
    image: eureka-server:latest
    ports:
      - 8761:8761
    networks:
      - my-network
    environment:
      SPRING_OPTS: |
        --eureka.instance.hostname=eurekaServer
  
  config-server:
    image: config-server:latest
    depends_on:
      - kafka
    ports:
      - 8888:8888
    networks:
      - my-network
    volumes:
          - ./ssh_conf:/root/.ssh
          - ./rasus_conf:/rasus_conf
    environment:
      SPRING_OPTS: |
        --spring.cloud.config.server.git.basedir=/rasus_conf
        --spring.kafka.bootstrap-servers=kafka:9092

networks:
  my-network:
    driver: bridge
    name: "my-network"
