
server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
        trace: false

  datasource:
    url: jdbc:h2:mem:readings
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
    show-sql: true

  application:
    name: humidity-sensor

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

 

