spring:
  application:
    name: aggregator
  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
    
    bus:
      refresh:
        enabled: true

  kafka: 
    bootstrap-servers: http://localhost:29092

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

app:
  temp:
    unit: C

management:
  endpoints:
    web:
      exposure:
        include: "*"
   

