
server:
  port: 8888
spring:
  cloud:
    config: 
      server:
        git:
          basedir: "/home/janroker/Documents/eclipse-workspace/rasus_lab3/rasus_conf"
          uri: git@github.com:janroker/rasus_conf.git
          clone-on-start: true
          default-label: master
          passphrase: rasus
      
    
    bus:
      enabled: true

  kafka: 
    bootstrap-servers: http://localhost:29092

